version: "2"

services:
  jenkins-core:
    image: jenkins/jenkins:lts
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    expose:
      - "8080"

